-- Campaign Generator: extend the campaigns table with strategic planning fields
-- and add a dedicated campaign_assets view for quick asset retrieval.
--
-- Design notes:
--   - concept, core_message, audience_angle, channel_strategy are top-level text
--     columns for fast display and filtering.
--   - content_ideas and calendar_draft are jsonb because they hold structured arrays
--     that vary in length per campaign.
--   - channels and cta_suggestions are simple text arrays.
--   - brand_profile_id wires the campaign to the Brand Intelligence Layer.

alter table public.campaigns
  add column if not exists concept           text,
  add column if not exists core_message      text,
  add column if not exists audience_angle    text,
  add column if not exists channel_strategy  text,
  add column if not exists offer             text,
  add column if not exists tone              text not null default 'Professional',
  add column if not exists channels          text[] not null default '{}',
  add column if not exists cta_suggestions   text[] not null default '{}',
  add column if not exists content_ideas     jsonb  not null default '[]'::jsonb,
  add column if not exists calendar_draft    jsonb  not null default '[]'::jsonb,
  add column if not exists brand_profile_id  uuid   references public.brand_profiles(id) on delete set null;

comment on column public.campaigns.concept          is 'One-paragraph campaign concept generated by the AI.';
comment on column public.campaigns.core_message     is 'The single central message that anchors every asset.';
comment on column public.campaigns.audience_angle   is 'Specific angle and framing for the target audience.';
comment on column public.campaigns.channel_strategy is 'Multi-channel approach and rationale.';
comment on column public.campaigns.offer            is 'The product, service, or offer being promoted.';
comment on column public.campaigns.tone             is 'Tone preference applied across all generated assets.';
comment on column public.campaigns.channels         is 'Selected channels: linkedin, instagram, email, blog, ads.';
comment on column public.campaigns.cta_suggestions  is 'AI-generated call-to-action options.';
comment on column public.campaigns.content_ideas    is 'Array of content idea objects [{id,title,channel,format,hook,week}].';
comment on column public.campaigns.calendar_draft   is 'Draft content calendar [{week,day,channel,title,content_type}].';
comment on column public.campaigns.brand_profile_id is 'FK to brand_profiles for automatic brand conditioning.';

-- Fast lookup of all assets belonging to a campaign via generated_outputs
create index if not exists campaigns_brand_profile_idx
  on public.campaigns (brand_profile_id)
  where brand_profile_id is not null;

create index if not exists campaigns_client_status_idx
  on public.campaigns (client_id, status, created_at desc);

-- Convenience view: campaign + its assets in one query
create or replace view public.campaign_assets_view as
  select
    c.id                as campaign_id,
    c.name              as campaign_name,
    c.client_id,
    c.project_id,
    c.status            as campaign_status,
    c.channels,
    c.tone,
    go.id               as asset_id,
    go.title            as asset_title,
    go.content          as asset_content,
    go.content_type     as asset_content_type,
    go.channel          as asset_channel,
    go.language         as asset_language,
    go.status           as asset_status,
    go.model            as asset_model,
    go.metadata         as asset_metadata,
    go.created_at       as asset_created_at,
    go.updated_at       as asset_updated_at,
    ci.id               as campaign_item_id,
    ci.due_date         as asset_due_date
  from public.campaigns c
  left join public.generated_outputs go
    on go.campaign_id = c.id
  left join public.campaign_items ci
    on ci.output_id = go.id and ci.campaign_id = c.id;

-- RLS policy on the new view is inherited from the underlying tables.
-- The view itself does not need separate RLS because both campaigns and
-- generated_outputs already enforce organization-level access.
